name: 95199651-9e81-4cae-a3a7-66398a9a5f62
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - pooch
  - py7zr
  - scikit-image
  - xmltodict
  - opencv
  - matplotlib
  - pytorch
  - torchvision
  - huggingface_hub
  - geopandas
  - pip
  - pip:
      - deepforest==1.4.0